### PR TITLE
Join route link fix

### LINKED ISSUE #95: Copying invitation link
Currently it doesn't join the room

### PR DESCRIPTION
**Pull request by CSimbulan**
Bug: users could join the assign roles lobby by directly pasting in a URL to the lobby, but they would skip the backend communication that adds the user to the mongoose match object.

Fix: The URL now sends them to the page with the match id input filled with the URL parameter. So now the user has to click the join button to perform the backend communication.

### CODE REVIEW

File: client/src/pages/Join.js [hunk 1]
```diff
@@ -101,10 +106,10 @@ function Join() {
       });
       console.log(response.status);
       const data = await response.json();
-     if (response.status === 200) {
+      if (response.status === 200) {
         setJoin(true);
         console.log('I JUST RAN');
```
Comment (dproc96) [inline client/src/pages/Join.js]: Outside scope, but can you remove this console.log?

File: client/src/pages/Join.js [hunk 2]
```diff
@@ -129,7 +134,7 @@ function Join() {
           </Typography>
           <TextField
             value={matchId}
-            onChange={onTextChange}
+            onChange={(e) => onTextChange(e)}
```
Comment (dproc96) [inline client/src/pages/Join.js]: This change shouldn't be necessary, you should be able to just pass the function directly

**Review by dproc96 — APPROVED** [review]
Looks good, had two small change requests though
